//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Texts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvariantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvariantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xecrets.Texts.Properties.InvariantResources", typeof(InvariantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #build-matching.
        /// </summary>
        internal static string CliVersionMismatchHelpId {
            get {
                return ResourceManager.GetString("CliVersionMismatchHelpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/customer-portal.
        /// </summary>
        internal static string CustomerPortalUrl {
            get {
                return ResourceManager.GetString("CustomerPortalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xecrets Cli.
        /// </summary>
        internal static string DisplayNameCliTools {
            get {
                return ResourceManager.GetString("DisplayNameCliTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xecrets Ez.
        /// </summary>
        internal static string DisplayNameProgram {
            get {
                return ResourceManager.GetString("DisplayNameProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK API.
        /// </summary>
        internal static string DisplayNameSdkApi {
            get {
                return ResourceManager.GetString("DisplayNameSdkApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/ez-features.
        /// </summary>
        internal static string EzFeaturesUrl {
            get {
                return ResourceManager.GetString("EzFeaturesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/license?m={0}&amp;l={1}.
        /// </summary>
        internal static string GetLicenseUrlFormat {
            get {
                return ResourceManager.GetString("GetLicenseUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/license?d={0}&amp;g={1}.
        /// </summary>
        internal static string GetTrialUrlFormat {
            get {
                return ResourceManager.GetString("GetTrialUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/pricing.
        /// </summary>
        internal static string GetXecretsUrl {
            get {
                return ResourceManager.GetString("GetXecretsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #license.
        /// </summary>
        internal static string LicenseHelpId {
            get {
                return ResourceManager.GetString("LicenseHelpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English [English].
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français [French].
        /// </summary>
        internal static string MenuFrench {
            get {
                return ResourceManager.GetString("MenuFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch [German].
        /// </summary>
        internal static string MenuGerman {
            get {
                return ResourceManager.GetString("MenuGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano [Italian].
        /// </summary>
        internal static string MenuItalian {
            get {
                return ResourceManager.GetString("MenuItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski [Polish].
        /// </summary>
        internal static string MenuPolish {
            get {
                return ResourceManager.GetString("MenuPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português (Brasil) [Portuguese (Brazil)].
        /// </summary>
        internal static string MenuPortugueseBrasil {
            get {
                return ResourceManager.GetString("MenuPortugueseBrasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español [Spanish].
        /// </summary>
        internal static string MenuSpanish {
            get {
                return ResourceManager.GetString("MenuSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska [Swedish].
        /// </summary>
        internal static string MenuSwedish {
            get {
                return ResourceManager.GetString("MenuSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #reset.
        /// </summary>
        internal static string PasswordResetId {
            get {
                return ResourceManager.GetString("PasswordResetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/release-notes.
        /// </summary>
        internal static string ReleaseNotesUrl {
            get {
                return ResourceManager.GetString("ReleaseNotesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/review-us.
        /// </summary>
        internal static string RequestReviewUrl {
            get {
                return ResourceManager.GetString("RequestReviewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shamir&apos;s Secret Sharing.
        /// </summary>
        internal static string ShamirsSecretSharing {
            get {
                return ResourceManager.GetString("ShamirsSecretSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com.
        /// </summary>
        internal static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Cli Debug OFF.
        /// </summary>
        internal static string TurnDebugOff {
            get {
                return ResourceManager.GetString("TurnDebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Cli Debug ON.
        /// </summary>
        internal static string TurnDebugOn {
            get {
                return ResourceManager.GetString("TurnDebugOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/download?ezv={0}&amp;rid={1}.
        /// </summary>
        internal static string UrlDownloadXecretsFormat {
            get {
                return ResourceManager.GetString("UrlDownloadXecretsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.axantum.com/help.
        /// </summary>
        internal static string XecretsHelpUrl {
            get {
                return ResourceManager.GetString("XecretsHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/@xecrets.
        /// </summary>
        internal static string YouTubeVideosUrl {
            get {
                return ResourceManager.GetString("YouTubeVideosUrl", resourceCulture);
            }
        }
    }
}
