//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Texts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xecrets.Texts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free version!.
        /// </summary>
        internal static string BannerUnlicensedWarning {
            get {
                return ResourceManager.GetString("BannerUnlicensedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        internal static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        internal static string ButtonCopyAll {
            get {
                return ResourceManager.GetString("ButtonCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create.
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string ButtonFree {
            get {
                return ResourceManager.GetString("ButtonFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string ButtonGo {
            get {
                return ResourceManager.GetString("ButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string ButtonLicense {
            get {
                return ResourceManager.GetString("ButtonLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string ButtonPremium {
            get {
                return ResourceManager.GetString("ButtonPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset!.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Retry.
        /// </summary>
        internal static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As….
        /// </summary>
        internal static string ButtonSaveAs {
            get {
                return ResourceManager.GetString("ButtonSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Version {0} of Xecrets Cli found at &quot;{1}&quot; does not match the version {2} of Xecrets Ez. This is not recommended since it may cause problems.
        ///
        ///Would you like to view a help page with more information?.
        /// </summary>
        internal static string CliVersionMismatchWarning {
            get {
                return ResourceManager.GetString("CliVersionMismatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ConfirmationQuestion {
            get {
                return ResourceManager.GetString("ConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra decryption passwords: {0}..
        /// </summary>
        internal static string DecryptionPasswordsAboutFormat {
            get {
                return ResourceManager.GetString("DecryptionPasswordsAboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not in the correct format!.
        /// </summary>
        internal static string DialogInputValidationError {
            get {
                return ResourceManager.GetString("DialogInputValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the license key from our license page (the link looks like {1}/license?s=2Rl7q1Gr…), then return here. If you already have the link, open it in your browser now. Otherwise, visit {0} and follow the instructions to get the correct link..
        /// </summary>
        internal static string DialogInstructionEnterLicenseFormat {
            get {
                return ResourceManager.GetString("DialogInstructionEnterLicenseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings directory:.
        /// </summary>
        internal static string DialogLabelAppSettingsDirectory {
            get {
                return ResourceManager.GetString("DialogLabelAppSettingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory:.
        /// </summary>
        internal static string DialogLabelCurrentDirectory {
            get {
                return ResourceManager.GetString("DialogLabelCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original start folder:.
        /// </summary>
        internal static string DialogLabelRealStartFolder {
            get {
                return ResourceManager.GetString("DialogLabelRealStartFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start command:.
        /// </summary>
        internal static string DialogLabelStartCommand {
            get {
                return ResourceManager.GetString("DialogLabelStartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in settings.
        /// </summary>
        internal static string DialogSavePasswordPermanently {
            get {
                return ResourceManager.GetString("DialogSavePasswordPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a decryption password.
        /// </summary>
        internal static string DialogTextAddPassword {
            get {
                return ResourceManager.GetString("DialogTextAddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string DialogTextAllFiles {
            get {
                return ResourceManager.GetString("DialogTextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Xecrets Cli found at &quot;{0}&quot; with API version {1}, but version {2}.[&gt;={3}] is required.\n\nUpdate Xecrets Cli, or remove it and use the one included in the app..
        /// </summary>
        internal static string DialogTextCliApiVersionError {
            get {
                return ResourceManager.GetString("DialogTextCliApiVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have downgraded to an older version. This can happen if multiple versions are installed. Do you really want to continue with this version?.
        /// </summary>
        internal static string DialogTextDowngradedVersionWarning {
            get {
                return ResourceManager.GetString("DialogTextDowngradedVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop or paste files here….
        /// </summary>
        internal static string DialogTextDropOrPasteTitle {
            get {
                return ResourceManager.GetString("DialogTextDropOrPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop or paste files here to encrypt or decrypt them. Use keyboard {0} button to decrypt a single file, otherwise it opens..
        /// </summary>
        internal static string DialogTextDropOrPasteToolTip {
            get {
                return ResourceManager.GetString("DialogTextDropOrPasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted files.
        /// </summary>
        internal static string DialogTextEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogTextEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Premium license.
        /// </summary>
        internal static string DialogTextEnterLicense {
            get {
                return ResourceManager.GetString("DialogTextEnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your premium license will expire on {0}. To keep using premium features, please renew your license in the app after it expires..
        /// </summary>
        internal static string DialogTextExpiresSoonInfoFormat {
            get {
                return ResourceManager.GetString("DialogTextExpiresSoonInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) do not exist, the action was canceled..
        /// </summary>
        internal static string DialogTextFileDoesNotExist {
            get {
                return ResourceManager.GetString("DialogTextFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) are read-only, the destination directory is not writeable or you do not have sufficient permissions. The action was canceled..
        /// </summary>
        internal static string DialogTextInsufficientRights {
            get {
                return ResourceManager.GetString("DialogTextInsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt and open failed.
        /// </summary>
        internal static string DialogTextOpenFailed {
            get {
                return ResourceManager.GetString("DialogTextOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized temporary files remain..
        /// </summary>
        internal static string DialogTextOrphanedDocumentsFiles {
            get {
                return ResourceManager.GetString("DialogTextOrphanedDocumentsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste files here….
        /// </summary>
        internal static string DialogTextPasteOnlyTitle {
            get {
                return ResourceManager.GetString("DialogTextPasteOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste files here to encrypt or decrypt them. Use keyboard {0} to decrypt a single file, otherwise it opens..
        /// </summary>
        internal static string DialogTextPasteOnlyToolTip {
            get {
                return ResourceManager.GetString("DialogTextPasteOnlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found and imported account keys from AxCrypt. You may still need to provide the original password a file was encrypted with if the AxCrypt password was reset, changed or is different from the Xecrets Ez password..
        /// </summary>
        internal static string DialogTextPrivateKeysImported {
            get {
                return ResourceManager.GetString("DialogTextPrivateKeysImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) require sandbox folder access to encrypt, decrypt, wipe or rename. The action was canceled. See {0}..
        /// </summary>
        internal static string DialogTextRelatedAccess {
            get {
                return ResourceManager.GetString("DialogTextRelatedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and temp files will be stored on a removable drive, not your main drive. Continue?.
        /// </summary>
        internal static string DialogTextRemovableDriveFirstWarning {
            get {
                return ResourceManager.GetString("DialogTextRemovableDriveFirstWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before unplugging it, make sure to exit the app and eject the drive safely to avoid data loss..
        /// </summary>
        internal static string DialogTextRemovableDriveUnplugWarning {
            get {
                return ResourceManager.GetString("DialogTextRemovableDriveUnplugWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) are system protected, the action was canceled..
        /// </summary>
        internal static string DialogTextSystemProtected {
            get {
                return ResourceManager.GetString("DialogTextSystemProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) were not encrypted. Encryption limit is 1 MB. See About..
        /// </summary>
        internal static string DialogTextTooLargeForLicense {
            get {
                return ResourceManager.GetString("DialogTextTooLargeForLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) could not be decrypted. Try adding an alternative password..
        /// </summary>
        internal static string DialogTextUnknownPassword {
            get {
                return ResourceManager.GetString("DialogTextUnknownPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be opened. Try decrypting with an alternative password first..
        /// </summary>
        internal static string DialogTextWrongPasswordOpen {
            get {
                return ResourceManager.GetString("DialogTextWrongPasswordOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get subscription license.
        /// </summary>
        internal static string DialogTitleFetchLicense {
            get {
                return ResourceManager.GetString("DialogTitleFetchLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running from removable drive!.
        /// </summary>
        internal static string DialogTitleRemovableDrive {
            get {
                return ResourceManager.GetString("DialogTitleRemovableDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder.
        /// </summary>
        internal static string DialogTitleSelectDestinationFolder {
            get {
                return ResourceManager.GetString("DialogTitleSelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to decrypt.
        /// </summary>
        internal static string DialogTitleSelectFilesToDecrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to encrypt.
        /// </summary>
        internal static string DialogTitleSelectFilesToEncrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to re-encrypt.
        /// </summary>
        internal static string DialogTitleSelectFilesToReEncrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToReEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to wipe.
        /// </summary>
        internal static string DialogTitleSelectFilesToWipe {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file to open.
        /// </summary>
        internal static string DialogTitleSelectFileToOpen {
            get {
                return ResourceManager.GetString("DialogTitleSelectFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string DialogTitleSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already signed in. Look for the app behind another window, on another screen, among minimized apps or in the system tray and show the window from there..
        /// </summary>
        internal static string DialogValidationAlreadySignedIn {
            get {
                return ResourceManager.GetString("DialogValidationAlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the password again.
        /// </summary>
        internal static string DialogValidationConfirmPassword {
            get {
                return ResourceManager.GetString("DialogValidationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string DialogValidationInvalidEmail {
            get {
                return ResourceManager.GetString("DialogValidationInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string DialogValidationPasswordRequired {
            get {
                return ResourceManager.GetString("DialogValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        internal static string DialogValidationWrongPassword {
            get {
                return ResourceManager.GetString("DialogValidationWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the YubiKey configuration, you must first remove the existing configuration..
        /// </summary>
        internal static string DialogYubiKeyChangeConfiguration {
            get {
                return ResourceManager.GetString("DialogYubiKeyChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the PIN, PUK, or Management Key, get the Yubico Authenticator app and go to Certificates settings. For details, click the help icon..
        /// </summary>
        internal static string DialogYubiKeyDefaultChangeInfo {
            get {
                return ResourceManager.GetString("DialogYubiKeyDefaultChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the YubiKey configuration?.
        /// </summary>
        internal static string DialogYubiKeyDisable {
            get {
                return ResourceManager.GetString("DialogYubiKeyDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable this YubiKey for signing in?.
        /// </summary>
        internal static string DialogYubiKeyEnable {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to use this YubiKey. There may not be any slots available..
        /// </summary>
        internal static string DialogYubiKeyEnabledFailed {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnabledFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter YubiKey PIV hex management key:.
        /// </summary>
        internal static string DialogYubiKeyEnterKeyTitle {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnterKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter YubiKey PIV PIN:.
        /// </summary>
        internal static string DialogYubiKeyEnterPinTitle {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnterPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for YubiKey….
        /// </summary>
        internal static string DialogYubiKeyLooking {
            get {
                return ResourceManager.GetString("DialogYubiKeyLooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PIV management key has it&apos;s default value 3 x 0102030405060708, it should be changed!.
        /// </summary>
        internal static string DialogYubiKeyManagementKeyDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyManagementKeyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required features are missing from this YubiKey..
        /// </summary>
        internal static string DialogYubiKeyMissingFeatures {
            get {
                return ResourceManager.GetString("DialogYubiKeyMissingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no YubiKey connected!.
        /// </summary>
        internal static string DialogYubiKeyNotConnected {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This YubiKey is not yet initialized for use..
        /// </summary>
        internal static string DialogYubiKeyNotInitialized {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This YubiKey is not supported!.
        /// </summary>
        internal static string DialogYubiKeyNotSupported {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this YubiKey and a touch is required to sign in..
        /// </summary>
        internal static string DialogYubiKeyOnlyTouch {
            get {
                return ResourceManager.GetString("DialogYubiKeyOnlyTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only this YubiKey is required to sign in..
        /// </summary>
        internal static string DialogYubiKeyOpenSecurity {
            get {
                return ResourceManager.GetString("DialogYubiKeyOpenSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that pcscd / pcsc-lite is installed and the daemon is running. Click the help icon for more information about YubiKey and Linux..
        /// </summary>
        internal static string DialogYubiKeyPcscMissing {
            get {
                return ResourceManager.GetString("DialogYubiKeyPcscMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PIV PIN has it&apos;s default value 123456, it should be changed!.
        /// </summary>
        internal static string DialogYubiKeyPinDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyPinDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This YubiKey and the PIN is required to sign in..
        /// </summary>
        internal static string DialogYubiKeyPinRequired {
            get {
                return ResourceManager.GetString("DialogYubiKeyPinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIV slot {0} is currently used or possible to use..
        /// </summary>
        internal static string DialogYubiKeyPivSlotUsedFormat {
            get {
                return ResourceManager.GetString("DialogYubiKeyPivSlotUsedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PIV PUK has it&apos;s default value 12345678, it should be changed!.
        /// </summary>
        internal static string DialogYubiKeyPukDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyPukDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use YubiKey, the Microsoft Visual C++ Redistributable must be installed. Download it from {0}, run the installer, and restart the application..
        /// </summary>
        internal static string DialogYubiKeyRedistributableMissing {
            get {
                return ResourceManager.GetString("DialogYubiKeyRedistributableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how you want to use your YubiKey..
        /// </summary>
        internal static string DialogYubiKeySelectMode {
            get {
                return ResourceManager.GetString("DialogYubiKeySelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app can’t use a YubiKey on this operating system..
        /// </summary>
        internal static string DialogYubiKeyServiceUnsupported {
            get {
                return ResourceManager.GetString("DialogYubiKeyServiceUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please touch the YubiKey….
        /// </summary>
        internal static string DialogYubiKeyTouchPrompt {
            get {
                return ResourceManager.GetString("DialogYubiKeyTouchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this again.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try premium free for 3 days? No credit card required..
        /// </summary>
        internal static string DownloadFreeTrialQuestion {
            get {
                return ResourceManager.GetString("DownloadFreeTrialQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shares could not be combined. Please check the shares and try again..
        /// </summary>
        internal static string ErrorCombiningShares {
            get {
                return ResourceManager.GetString("ErrorCombiningShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate shares were removed..
        /// </summary>
        internal static string ErrorDuplicatesRemoved {
            get {
                return ResourceManager.GetString("ErrorDuplicatesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your free trial license has expired. Do you want to view the subscription information web page?.
        /// </summary>
        internal static string ExpirationCheckPurchaseWarning {
            get {
                return ResourceManager.GetString("ExpirationCheckPurchaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired. Do you want to download an updated license?.
        /// </summary>
        internal static string ExpirationCheckWarning {
            get {
                return ResourceManager.GetString("ExpirationCheckWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to hide all premium features?.
        /// </summary>
        internal static string FeatureNotFreeHideQuestion {
            get {
                return ResourceManager.GetString("FeatureNotFreeHideQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard encryption and decryption is of course always free!
        ///
        ///If you like the program and would like to enable all features, please support
        ///us by purchasing a subscription at {0}.
        ///
        ///It&apos;s not free, but it&apos;s not expensive either and totally worth it we think!.
        /// </summary>
        internal static string FeatureNotFreeInformation {
            get {
                return ResourceManager.GetString("FeatureNotFreeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this premium feature is not available in the free version..
        /// </summary>
        internal static string FeatureNotFreeShortInformation {
            get {
                return ResourceManager.GetString("FeatureNotFreeShortInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Feature not available.
        /// </summary>
        internal static string FeatureNotFreeTitle {
            get {
                return ResourceManager.GetString("FeatureNotFreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string FilesCanceledMessage {
            get {
                return ResourceManager.GetString("FilesCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files|{0} file|{0} files.
        /// </summary>
        internal static string FilesProcessedMessageFormat {
            get {
                return ResourceManager.GetString("FilesProcessedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A browser window will open. Copy the license from there, return here and paste it..
        /// </summary>
        internal static string GetLicenseTooltip {
            get {
                return ResourceManager.GetString("GetLicenseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile.
        /// </summary>
        internal static string HeadingCreateNewUser {
            get {
                return ResourceManager.GetString("HeadingCreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup a local profile.
        /// </summary>
        internal static string HeadingCreateUserFirstTimeSetup {
            get {
                return ResourceManager.GetString("HeadingCreateUserFirstTimeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password!.
        /// </summary>
        internal static string HeadingEmergencyReset {
            get {
                return ResourceManager.GetString("HeadingEmergencyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is invalid or expired..
        /// </summary>
        internal static string InvalidLicenseIgnored {
            get {
                return ResourceManager.GetString("InvalidLicenseIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no saved passwords to clear.|There is one saved password. Clear it?|There are {0} passwords saved. Clear them all?.
        /// </summary>
        internal static string LabelDecryptionPasswordCountFormat {
            get {
                return ResourceManager.GetString("LabelDecryptionPasswordCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 4 digits of credit card, or empty..
        /// </summary>
        internal static string LabelLast4 {
            get {
                return ResourceManager.GetString("LabelLast4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret.
        /// </summary>
        internal static string LabelTheSecret {
            get {
                return ResourceManager.GetString("LabelTheSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License for {licensee} valid to {expiration}, thank you!.
        /// </summary>
        internal static string LicensedBlurb {
            get {
                return ResourceManager.GetString("LicensedBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License for {licensee} expired at {expiration}.\nFree version, some features unavailable.\nSee https://www.axantum.com/ ..
        /// </summary>
        internal static string LicensedExpiredBlurb {
            get {
                return ResourceManager.GetString("LicensedExpiredBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License &quot;{product}&quot; for {licensee} is not valid for this software. Free version, some features unavailable.\nSee https://www.axantum.com/ ..
        /// </summary>
        internal static string LicenseNotValidForProductBlurb {
            get {
                return ResourceManager.GetString("LicenseNotValidForProductBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add decryption password….
        /// </summary>
        internal static string MenuAddPassword {
            get {
                return ResourceManager.GetString("MenuAddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to _premium….
        /// </summary>
        internal static string MenuBuyNow {
            get {
                return ResourceManager.GetString("MenuBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change _email….
        /// </summary>
        internal static string MenuChangeEmail {
            get {
                return ResourceManager.GetString("MenuChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change _password….
        /// </summary>
        internal static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all _messages again.
        /// </summary>
        internal static string MenuClearDontShowAgain {
            get {
                return ResourceManager.GetString("MenuClearDontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear decryption passwords….
        /// </summary>
        internal static string MenuClearPasswords {
            get {
                return ResourceManager.GetString("MenuClearPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear recent list….
        /// </summary>
        internal static string MenuClearRecent {
            get {
                return ResourceManager.GetString("MenuClearRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste license from _clipboard.
        /// </summary>
        internal static string MenuClipboardLicense {
            get {
                return ResourceManager.GetString("MenuClipboardLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close all.
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ombine secret shares….
        /// </summary>
        internal static string MenuCombineShares {
            get {
                return ResourceManager.GetString("MenuCombineShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create secret shares….
        /// </summary>
        internal static string MenuCreateShares {
            get {
                return ResourceManager.GetString("MenuCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create new profile….
        /// </summary>
        internal static string MenuCreateUser {
            get {
                return ResourceManager.GetString("MenuCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer _portal….
        /// </summary>
        internal static string MenuCustomerPortal {
            get {
                return ResourceManager.GetString("MenuCustomerPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Decrypt….
        /// </summary>
        internal static string MenuDecrypt {
            get {
                return ResourceManager.GetString("MenuDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt f_older files….
        /// </summary>
        internal static string MenuDecryptFolder {
            get {
                return ResourceManager.GetString("MenuDecryptFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _update….
        /// </summary>
        internal static string MenuDownload {
            get {
                return ResourceManager.GetString("MenuDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Encrypt….
        /// </summary>
        internal static string MenuEncrypt {
            get {
                return ResourceManager.GetString("MenuEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt _copy….
        /// </summary>
        internal static string MenuEncryptCopy {
            get {
                return ResourceManager.GetString("MenuEncryptCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt _copy to share….
        /// </summary>
        internal static string MenuEncryptCopyFor {
            get {
                return ResourceManager.GetString("MenuEncryptCopyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt or decrypt _text….
        /// </summary>
        internal static string MenuEncryptDecryptText {
            get {
                return ResourceManager.GetString("MenuEncryptDecryptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt _folder files….
        /// </summary>
        internal static string MenuEncryptFolder {
            get {
                return ResourceManager.GetString("MenuEncryptFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate _Premium….
        /// </summary>
        internal static string MenuEnterLicense {
            get {
                return ResourceManager.GetString("MenuEnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Video guides….
        /// </summary>
        internal static string MenuHelpVideos {
            get {
                return ResourceManager.GetString("MenuHelpVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit after inactivity….
        /// </summary>
        internal static string MenuInactivityExit {
            get {
                return ResourceManager.GetString("MenuInactivityExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string MenuInactivityNever {
            get {
                return ResourceManager.GetString("MenuInactivityNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string MenuInactivityTimeoutValueFormat {
            get {
                return ResourceManager.GetString("MenuInactivityTimeoutValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your subscription premium _license….
        /// </summary>
        internal static string MenuLicense {
            get {
                return ResourceManager.GetString("MenuLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View secret shares….
        /// </summary>
        internal static string MenuLoadShares {
            get {
                return ResourceManager.GetString("MenuLoadShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open….
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _recent.
        /// </summary>
        internal static string MenuOpenRecent {
            get {
                return ResourceManager.GetString("MenuOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences….
        /// </summary>
        internal static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename randomly….
        /// </summary>
        internal static string MenuRandomRename {
            get {
                return ResourceManager.GetString("MenuRandomRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Re-encrypt….
        /// </summary>
        internal static string MenuReEncryptFiles {
            get {
                return ResourceManager.GetString("MenuReEncryptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Re-encrypt folder files.
        /// </summary>
        internal static string MenuReEncryptFolder {
            get {
                return ResourceManager.GetString("MenuReEncryptFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show.
        /// </summary>
        internal static string MenuShow {
            get {
                return ResourceManager.GetString("MenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Suggest password….
        /// </summary>
        internal static string MenuSuggestPassword {
            get {
                return ResourceManager.GetString("MenuSuggestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme….
        /// </summary>
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your 3 day _free premium license….
        /// </summary>
        internal static string MenuTrialDownload {
            get {
                return ResourceManager.GetString("MenuTrialDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User.
        /// </summary>
        internal static string MenuUser {
            get {
                return ResourceManager.GetString("MenuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete securely….
        /// </summary>
        internal static string MenuWipe {
            get {
                return ResourceManager.GetString("MenuWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _YubiKey configuration….
        /// </summary>
        internal static string MenuYubiKey {
            get {
                return ResourceManager.GetString("MenuYubiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted data is not correctly formatted..
        /// </summary>
        internal static string MessageFileFormatError {
            get {
                return ResourceManager.GetString("MessageFileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial 16 bytes are wrong, it is probably some other kind of data or severely damaged..
        /// </summary>
        internal static string MessageNotEncrypted {
            get {
                return ResourceManager.GetString("MessageNotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license key is not in the correct format..
        /// </summary>
        internal static string MessageTextBadLicenseString {
            get {
                return ResourceManager.GetString("MessageTextBadLicenseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s {0} files!.
        /// </summary>
        internal static string MessageTextConfirmManyFilesFormat {
            get {
                return ResourceManager.GetString("MessageTextConfirmManyFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That includes a directory..
        /// </summary>
        internal static string MessageTextConfirmPasteDirectory {
            get {
                return ResourceManager.GetString("MessageTextConfirmPasteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be undone..
        /// </summary>
        internal static string MessageTextConfirmWipe {
            get {
                return ResourceManager.GetString("MessageTextConfirmWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string MessageTextForgotPassword {
            get {
                return ResourceManager.GetString("MessageTextForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to launch your web browser to activate your license?.
        /// </summary>
        internal static string MessageTextLaunchLicensePage {
            get {
                return ResourceManager.GetString("MessageTextLaunchLicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is damaged, the length is zero bytes..
        /// </summary>
        internal static string MessageZeroLength {
            get {
                return ResourceManager.GetString("MessageZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both encrypted and plain files are included. The plain files will be encrypted, and the already encrypted will be unchanged..
        /// </summary>
        internal static string MixedFilesWarning {
            get {
                return ResourceManager.GetString("MixedFilesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) couldn&apos;t be closed and remain open!.
        /// </summary>
        internal static string OpenFilesRemainMessage {
            get {
                return ResourceManager.GetString("OpenFilesRemainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was canceled during processing of &quot;{0}&quot;. Check and verify!.
        /// </summary>
        internal static string OperationCanceledFormat {
            get {
                return ResourceManager.GetString("OperationCanceledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        internal static string PlaceholderLoading {
            get {
                return ResourceManager.GetString("PlaceholderLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra private keys: {0} of {1} total..
        /// </summary>
        internal static string PrivateKeysAboutFormat {
            get {
                return ResourceManager.GetString("PrivateKeysAboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a share.
        /// </summary>
        internal static string PromptEnterFirstShare {
            get {
                return ResourceManager.GetString("PromptEnterFirstShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the remaining required shares.
        /// </summary>
        internal static string PromptEnterRemainingShares {
            get {
                return ResourceManager.GetString("PromptEnterRemainingShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required shares.
        /// </summary>
        internal static string PromptRequiredShares {
            get {
                return ResourceManager.GetString("PromptRequiredShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shares.
        /// </summary>
        internal static string PromptTotalShares {
            get {
                return ResourceManager.GetString("PromptTotalShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running a new version! Would you like to see the release notes?.
        /// </summary>
        internal static string ReleaseNotesInformation {
            get {
                return ResourceManager.GetString("ReleaseNotesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please help us by reviewing and rating the app!.
        /// </summary>
        internal static string RequestReviewQuestion {
            get {
                return ResourceManager.GetString("RequestReviewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share any secret.
        /// </summary>
        internal static string SelectShareAny {
            get {
                return ResourceManager.GetString("SelectShareAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share sign in password.
        /// </summary>
        internal static string SelectShareSignIn {
            get {
                return ResourceManager.GetString("SelectShareSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _System.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for more information….
        /// </summary>
        internal static string TipMoreHelp {
            get {
                return ResourceManager.GetString("TipMoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a password is only for decryption, when you receive files from someone else or you have used another password previously. It does not affect encryption..
        /// </summary>
        internal static string ToolTipAddPassword {
            get {
                return ResourceManager.GetString("ToolTipAddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear decryption passwords saved in settings. You can always add them back again..
        /// </summary>
        internal static string ToolTipClearPasswords {
            get {
                return ResourceManager.GetString("ToolTipClearPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the required number of shares to combine them and view the secret..
        /// </summary>
        internal static string ToolTipCombineShares {
            get {
                return ResourceManager.GetString("ToolTipCombineShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the suggested password and close the dialog..
        /// </summary>
        internal static string ToolTipCopySuggested {
            get {
                return ResourceManager.GetString("ToolTipCopySuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split a secret into shares, specifying how many shares and how many are required to recover the secret..
        /// </summary>
        internal static string ToolTipCreateShares {
            get {
                return ResourceManager.GetString("ToolTipCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make text and window smaller..
        /// </summary>
        internal static string ToolTipDecreaseScaleFactor {
            get {
                return ResourceManager.GetString("ToolTipDecreaseScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not used for sending emails. It&apos;s an identifier for your local profile in the software and for sharing with others..
        /// </summary>
        internal static string ToolTipEmail {
            get {
                return ResourceManager.GetString("ToolTipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a new master password. Warning! The old password is still needed to decrypt previously encrypted files!.
        /// </summary>
        internal static string ToolTipEmergencyReset {
            get {
                return ResourceManager.GetString("ToolTipEmergencyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write or copy/paste text to encrypt or decrypt. The password will be used to encrypt or decrypt the text, and should be shared in a separate channel between the sender and recipient. Always include the BEGIN header and the END footer with the encrypted text..
        /// </summary>
        internal static string ToolTipEncryptDecryptText {
            get {
                return ResourceManager.GetString("ToolTipEncryptDecryptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your subscription license has expired, or you are using a new device, you must fetch a license from the server. Provide the information here and follow the instructions..
        /// </summary>
        internal static string ToolTipGetLicense {
            get {
                return ResourceManager.GetString("ToolTipGetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the last 4 digits empty if you didn&apos;t use a card or don&apos;t recall them..
        /// </summary>
        internal static string ToolTipGetLicenseNoCard {
            get {
                return ResourceManager.GetString("ToolTipGetLicenseNoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password..
        /// </summary>
        internal static string ToolTipHidePassword {
            get {
                return ResourceManager.GetString("ToolTipHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide premium features unavailable in the free version..
        /// </summary>
        internal static string ToolTipHidePremium {
            get {
                return ResourceManager.GetString("ToolTipHidePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make text and window bigger..
        /// </summary>
        internal static string ToolTipIncreaseScaleFactor {
            get {
                return ResourceManager.GetString("ToolTipIncreaseScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your master password. Make it strong, write it down and keep it safe..
        /// </summary>
        internal static string ToolTipMasterPassword {
            get {
                return ResourceManager.GetString("ToolTipMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password..
        /// </summary>
        internal static string ToolTipShowPassword {
            get {
                return ResourceManager.GetString("ToolTipShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all premium features..
        /// </summary>
        internal static string ToolTipShowPremium {
            get {
                return ResourceManager.GetString("ToolTipShowPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in ensures you are using the correct password for encryption, and that you don&apos;t need to retype the password each time. This is the master password for all encryption. The sign in is only local to the app..
        /// </summary>
        internal static string ToolTipSignIn {
            get {
                return ResourceManager.GetString("ToolTipSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest a password..
        /// </summary>
        internal static string ToolTipSuggestMasterPassword {
            get {
                return ResourceManager.GetString("ToolTipSuggestMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View previously created shares, and send or save them to different places..
        /// </summary>
        internal static string ToolTipViewShares {
            get {
                return ResourceManager.GetString("ToolTipViewShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable the use of a YubiKey for sign in. Use the Yubico Authenticator or other utilities to reset, change and inspect the YubiKey PIV configuration in more detail..
        /// </summary>
        internal static string ToolTipYubiKeySetup {
            get {
                return ResourceManager.GetString("ToolTipYubiKeySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free version, some features are unavailable.
        ///
        ///Please buy a license. See https://www.axantum.com/ ..
        /// </summary>
        internal static string UnlicensedBlurb {
            get {
                return ResourceManager.GetString("UnlicensedBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to check if there&apos;s an update available?.
        /// </summary>
        internal static string UpdateCheckInformation {
            get {
                return ResourceManager.GetString("UpdateCheckInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check.
        /// </summary>
        internal static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save or distribute these shares to different people or places. At least {0} shares are required to recover the secret..
        /// </summary>
        internal static string ViewSharesDescriptionFormat {
            get {
                return ResourceManager.GetString("ViewSharesDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string WatermarkConfirmPassword {
            get {
                return ResourceManager.GetString("WatermarkConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string WatermarkCurrentPassword {
            get {
                return ResourceManager.GetString("WatermarkCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string WatermarkEmail {
            get {
                return ResourceManager.GetString("WatermarkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license key goes here: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ….
        /// </summary>
        internal static string WatermarkEnterLicenseHere {
            get {
                return ResourceManager.GetString("WatermarkEnterLicenseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 digits.
        /// </summary>
        internal static string WatermarkLast4 {
            get {
                return ResourceManager.GetString("WatermarkLast4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string WatermarkNewPassword {
            get {
                return ResourceManager.GetString("WatermarkNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string WatermarkPassword {
            get {
                return ResourceManager.GetString("WatermarkPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any password or secret….
        /// </summary>
        internal static string WatermarkPasswordSecret {
            get {
                return ResourceManager.GetString("WatermarkPasswordSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to share.
        /// </summary>
        internal static string WatermarkPasswordShare {
            get {
                return ResourceManager.GetString("WatermarkPasswordShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more selected files are empty. They might be damaged..
        /// </summary>
        internal static string ZeroLengthWarning {
            get {
                return ResourceManager.GetString("ZeroLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open files|One open file…|{0} Open files….
        /// </summary>
        internal static string ZzCommandBarContentFilesOpenFormat {
            get {
                return ResourceManager.GetString("ZzCommandBarContentFilesOpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to {0}.
        /// </summary>
        internal static string ZzHeadingSignInFormat {
            get {
                return ResourceManager.GetString("ZzHeadingSignInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} API version:.
        /// </summary>
        internal static string ZzLabelCliToolApiVersionFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolApiVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} information:.
        /// </summary>
        internal static string ZzLabelCliToolInformationFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolInformationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} path:.
        /// </summary>
        internal static string ZzLabelCliToolPathFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} version:.
        /// </summary>
        internal static string ZzLabelSdkApiVersionFormat {
            get {
                return ResourceManager.GetString("ZzLabelSdkApiVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string ZzTitleAboutFormat {
            get {
                return ResourceManager.GetString("ZzTitleAboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0} {2}.
        /// </summary>
        internal static string ZzTitleProgramVersionNameFormat {
            get {
                return ResourceManager.GetString("ZzTitleProgramVersionNameFormat", resourceCulture);
            }
        }
    }
}
