//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Texts.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xecrets.Texts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        internal static string HeadingCreateUserFirstTimeSetup {
            get {
                return ResourceManager.GetString("HeadingCreateUserFirstTimeSetup", resourceCulture);
            }
        }
        
        internal static string ToolTipEmail {
            get {
                return ResourceManager.GetString("ToolTipEmail", resourceCulture);
            }
        }
        
        internal static string WatermarkEmail {
            get {
                return ResourceManager.GetString("WatermarkEmail", resourceCulture);
            }
        }
        
        internal static string PlaceholderLoading {
            get {
                return ResourceManager.GetString("PlaceholderLoading", resourceCulture);
            }
        }
        
        internal static string ToolTipMasterPassword {
            get {
                return ResourceManager.GetString("ToolTipMasterPassword", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        internal static string MenuDecrypt {
            get {
                return ResourceManager.GetString("MenuDecrypt", resourceCulture);
            }
        }
        
        internal static string MenuEncrypt {
            get {
                return ResourceManager.GetString("MenuEncrypt", resourceCulture);
            }
        }
        
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        internal static string WatermarkPassword {
            get {
                return ResourceManager.GetString("WatermarkPassword", resourceCulture);
            }
        }
        
        internal static string WatermarkConfirmPassword {
            get {
                return ResourceManager.GetString("WatermarkConfirmPassword", resourceCulture);
            }
        }
        
        internal static string ZzTitleAboutFormat {
            get {
                return ResourceManager.GetString("ZzTitleAboutFormat", resourceCulture);
            }
        }
        
        internal static string ZzLabelCliToolApiVersionFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolApiVersionFormat", resourceCulture);
            }
        }
        
        internal static string ZzLabelCliToolInformationFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolInformationFormat", resourceCulture);
            }
        }
        
        internal static string ZzLabelCliToolPathFormat {
            get {
                return ResourceManager.GetString("ZzLabelCliToolPathFormat", resourceCulture);
            }
        }
        
        internal static string ZzLabelSdkApiVersionFormat {
            get {
                return ResourceManager.GetString("ZzLabelSdkApiVersionFormat", resourceCulture);
            }
        }
        
        internal static string ZzHeadingSignInFormat {
            get {
                return ResourceManager.GetString("ZzHeadingSignInFormat", resourceCulture);
            }
        }
        
        internal static string ZzTitleProgramVersionNameFormat {
            get {
                return ResourceManager.GetString("ZzTitleProgramVersionNameFormat", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        internal static string DialogTextAllFiles {
            get {
                return ResourceManager.GetString("DialogTextAllFiles", resourceCulture);
            }
        }
        
        internal static string DialogTextDowngradedVersionWarning {
            get {
                return ResourceManager.GetString("DialogTextDowngradedVersionWarning", resourceCulture);
            }
        }
        
        internal static string DialogTextEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogTextEncryptedFiles", resourceCulture);
            }
        }
        
        internal static string DialogValidationConfirmPassword {
            get {
                return ResourceManager.GetString("DialogValidationConfirmPassword", resourceCulture);
            }
        }
        
        internal static string DialogValidationInvalidEmail {
            get {
                return ResourceManager.GetString("DialogValidationInvalidEmail", resourceCulture);
            }
        }
        
        internal static string DialogValidationPasswordRequired {
            get {
                return ResourceManager.GetString("DialogValidationPasswordRequired", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFilesToDecrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToDecrypt", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFilesToEncrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToEncrypt", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFileToOpen {
            get {
                return ResourceManager.GetString("DialogTitleSelectFileToOpen", resourceCulture);
            }
        }
        
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        internal static string DialogValidationWrongPassword {
            get {
                return ResourceManager.GetString("DialogValidationWrongPassword", resourceCulture);
            }
        }
        
        internal static string DialogTextDropOrPasteTitle {
            get {
                return ResourceManager.GetString("DialogTextDropOrPasteTitle", resourceCulture);
            }
        }
        
        internal static string DialogTextDropOrPasteToolTip {
            get {
                return ResourceManager.GetString("DialogTextDropOrPasteToolTip", resourceCulture);
            }
        }
        
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        internal static string MenuShow {
            get {
                return ResourceManager.GetString("MenuShow", resourceCulture);
            }
        }
        
        internal static string ZzCommandBarContentFilesOpenFormat {
            get {
                return ResourceManager.GetString("ZzCommandBarContentFilesOpenFormat", resourceCulture);
            }
        }
        
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        internal static string LicensedBlurb {
            get {
                return ResourceManager.GetString("LicensedBlurb", resourceCulture);
            }
        }
        
        internal static string LicensedExpiredBlurb {
            get {
                return ResourceManager.GetString("LicensedExpiredBlurb", resourceCulture);
            }
        }
        
        internal static string LicenseNotValidForProductBlurb {
            get {
                return ResourceManager.GetString("LicenseNotValidForProductBlurb", resourceCulture);
            }
        }
        
        internal static string UnlicensedBlurb {
            get {
                return ResourceManager.GetString("UnlicensedBlurb", resourceCulture);
            }
        }
        
        internal static string BannerUnlicensedWarning {
            get {
                return ResourceManager.GetString("BannerUnlicensedWarning", resourceCulture);
            }
        }
        
        internal static string DialogTextTooLargeForLicense {
            get {
                return ResourceManager.GetString("DialogTextTooLargeForLicense", resourceCulture);
            }
        }
        
        internal static string ToolTipDecreaseScaleFactor {
            get {
                return ResourceManager.GetString("ToolTipDecreaseScaleFactor", resourceCulture);
            }
        }
        
        internal static string ToolTipIncreaseScaleFactor {
            get {
                return ResourceManager.GetString("ToolTipIncreaseScaleFactor", resourceCulture);
            }
        }
        
        internal static string InvalidLicenseIgnored {
            get {
                return ResourceManager.GetString("InvalidLicenseIgnored", resourceCulture);
            }
        }
        
        internal static string DialogTextUnknownPassword {
            get {
                return ResourceManager.GetString("DialogTextUnknownPassword", resourceCulture);
            }
        }
        
        internal static string MenuAddPassword {
            get {
                return ResourceManager.GetString("MenuAddPassword", resourceCulture);
            }
        }
        
        internal static string DialogTextAddPassword {
            get {
                return ResourceManager.GetString("DialogTextAddPassword", resourceCulture);
            }
        }
        
        internal static string DialogTextOpenFailed {
            get {
                return ResourceManager.GetString("DialogTextOpenFailed", resourceCulture);
            }
        }
        
        internal static string DialogLabelCurrentDirectory {
            get {
                return ResourceManager.GetString("DialogLabelCurrentDirectory", resourceCulture);
            }
        }
        
        internal static string DialogLabelStartCommand {
            get {
                return ResourceManager.GetString("DialogLabelStartCommand", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectDestinationFolder {
            get {
                return ResourceManager.GetString("DialogTitleSelectDestinationFolder", resourceCulture);
            }
        }
        
        internal static string MenuEncryptCopyFor {
            get {
                return ResourceManager.GetString("MenuEncryptCopyFor", resourceCulture);
            }
        }
        
        internal static string OpenFilesRemainMessage {
            get {
                return ResourceManager.GetString("OpenFilesRemainMessage", resourceCulture);
            }
        }
        
        internal static string DialogTextOrphanedDocumentsFiles {
            get {
                return ResourceManager.GetString("DialogTextOrphanedDocumentsFiles", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFilesToWipe {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToWipe", resourceCulture);
            }
        }
        
        internal static string MenuWipe {
            get {
                return ResourceManager.GetString("MenuWipe", resourceCulture);
            }
        }
        
        internal static string MessageTextConfirmWipe {
            get {
                return ResourceManager.GetString("MessageTextConfirmWipe", resourceCulture);
            }
        }
        
        internal static string DialogTextPasteOnlyTitle {
            get {
                return ResourceManager.GetString("DialogTextPasteOnlyTitle", resourceCulture);
            }
        }
        
        internal static string DialogTextPasteOnlyToolTip {
            get {
                return ResourceManager.GetString("DialogTextPasteOnlyToolTip", resourceCulture);
            }
        }
        
        internal static string DialogValidationAlreadySignedIn {
            get {
                return ResourceManager.GetString("DialogValidationAlreadySignedIn", resourceCulture);
            }
        }
        
        internal static string HeadingCreateNewUser {
            get {
                return ResourceManager.GetString("HeadingCreateNewUser", resourceCulture);
            }
        }
        
        internal static string MenuCreateUser {
            get {
                return ResourceManager.GetString("MenuCreateUser", resourceCulture);
            }
        }
        
        internal static string MenuUser {
            get {
                return ResourceManager.GetString("MenuUser", resourceCulture);
            }
        }
        
        internal static string MenuOpenRecent {
            get {
                return ResourceManager.GetString("MenuOpenRecent", resourceCulture);
            }
        }
        
        internal static string ButtonGo {
            get {
                return ResourceManager.GetString("ButtonGo", resourceCulture);
            }
        }
        
        internal static string FeatureNotFreeInformation {
            get {
                return ResourceManager.GetString("FeatureNotFreeInformation", resourceCulture);
            }
        }
        
        internal static string FeatureNotFreeTitle {
            get {
                return ResourceManager.GetString("FeatureNotFreeTitle", resourceCulture);
            }
        }
        
        internal static string DialogSavePasswordPermanently {
            get {
                return ResourceManager.GetString("DialogSavePasswordPermanently", resourceCulture);
            }
        }
        
        internal static string MenuEncryptCopy {
            get {
                return ResourceManager.GetString("MenuEncryptCopy", resourceCulture);
            }
        }
        
        internal static string DialogTextWrongPasswordOpen {
            get {
                return ResourceManager.GetString("DialogTextWrongPasswordOpen", resourceCulture);
            }
        }
        
        internal static string UpdateCheckInformation {
            get {
                return ResourceManager.GetString("UpdateCheckInformation", resourceCulture);
            }
        }
        
        internal static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        internal static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        internal static string WatermarkCurrentPassword {
            get {
                return ResourceManager.GetString("WatermarkCurrentPassword", resourceCulture);
            }
        }
        
        internal static string WatermarkNewPassword {
            get {
                return ResourceManager.GetString("WatermarkNewPassword", resourceCulture);
            }
        }
        
        internal static string DialogTextFileDoesNotExist {
            get {
                return ResourceManager.GetString("DialogTextFileDoesNotExist", resourceCulture);
            }
        }
        
        internal static string DialogTextInsufficientRights {
            get {
                return ResourceManager.GetString("DialogTextInsufficientRights", resourceCulture);
            }
        }
        
        internal static string DialogTextSystemProtected {
            get {
                return ResourceManager.GetString("DialogTextSystemProtected", resourceCulture);
            }
        }
        
        internal static string DialogTextRelatedAccess {
            get {
                return ResourceManager.GetString("DialogTextRelatedAccess", resourceCulture);
            }
        }
        
        internal static string MessageTextConfirmManyFilesFormat {
            get {
                return ResourceManager.GetString("MessageTextConfirmManyFilesFormat", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleSelectFolder", resourceCulture);
            }
        }
        
        internal static string MenuDecryptFolder {
            get {
                return ResourceManager.GetString("MenuDecryptFolder", resourceCulture);
            }
        }
        
        internal static string MenuEncryptFolder {
            get {
                return ResourceManager.GetString("MenuEncryptFolder", resourceCulture);
            }
        }
        
        internal static string DialogTitleFetchLicense {
            get {
                return ResourceManager.GetString("DialogTitleFetchLicense", resourceCulture);
            }
        }
        
        internal static string LabelLast4 {
            get {
                return ResourceManager.GetString("LabelLast4", resourceCulture);
            }
        }
        
        internal static string WatermarkLast4 {
            get {
                return ResourceManager.GetString("WatermarkLast4", resourceCulture);
            }
        }
        
        internal static string GetLicenseTooltip {
            get {
                return ResourceManager.GetString("GetLicenseTooltip", resourceCulture);
            }
        }
        
        internal static string MenuBuyNow {
            get {
                return ResourceManager.GetString("MenuBuyNow", resourceCulture);
            }
        }
        
        internal static string MenuDownload {
            get {
                return ResourceManager.GetString("MenuDownload", resourceCulture);
            }
        }
        
        internal static string MenuLicense {
            get {
                return ResourceManager.GetString("MenuLicense", resourceCulture);
            }
        }
        
        internal static string FilesProcessedMessageFormat {
            get {
                return ResourceManager.GetString("FilesProcessedMessageFormat", resourceCulture);
            }
        }
        
        internal static string TipMoreHelp {
            get {
                return ResourceManager.GetString("TipMoreHelp", resourceCulture);
            }
        }
        
        internal static string ToolTipAddPassword {
            get {
                return ResourceManager.GetString("ToolTipAddPassword", resourceCulture);
            }
        }
        
        internal static string ToolTipSignIn {
            get {
                return ResourceManager.GetString("ToolTipSignIn", resourceCulture);
            }
        }
        
        internal static string ButtonFree {
            get {
                return ResourceManager.GetString("ButtonFree", resourceCulture);
            }
        }
        
        internal static string ButtonPremium {
            get {
                return ResourceManager.GetString("ButtonPremium", resourceCulture);
            }
        }
        
        internal static string ToolTipHidePremium {
            get {
                return ResourceManager.GetString("ToolTipHidePremium", resourceCulture);
            }
        }
        
        internal static string ToolTipShowPremium {
            get {
                return ResourceManager.GetString("ToolTipShowPremium", resourceCulture);
            }
        }
        
        internal static string LabelDecryptionPasswordCountFormat {
            get {
                return ResourceManager.GetString("LabelDecryptionPasswordCountFormat", resourceCulture);
            }
        }
        
        internal static string MenuClearPasswords {
            get {
                return ResourceManager.GetString("MenuClearPasswords", resourceCulture);
            }
        }
        
        internal static string ToolTipClearPasswords {
            get {
                return ResourceManager.GetString("ToolTipClearPasswords", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyDisable {
            get {
                return ResourceManager.GetString("DialogYubiKeyDisable", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyEnable {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnable", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyLooking {
            get {
                return ResourceManager.GetString("DialogYubiKeyLooking", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyNotConnected {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotConnected", resourceCulture);
            }
        }
        
        internal static string MenuYubiKey {
            get {
                return ResourceManager.GetString("MenuYubiKey", resourceCulture);
            }
        }
        
        internal static string ToolTipYubiKeySetup {
            get {
                return ResourceManager.GetString("ToolTipYubiKeySetup", resourceCulture);
            }
        }
        
        internal static string DialogInputValidationError {
            get {
                return ResourceManager.GetString("DialogInputValidationError", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyEnterKeyTitle {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnterKeyTitle", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyEnterPinTitle {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnterPinTitle", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyManagementKeyDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyManagementKeyDefault", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyMissingFeatures {
            get {
                return ResourceManager.GetString("DialogYubiKeyMissingFeatures", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyNotInitialized {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotInitialized", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyNotSupported {
            get {
                return ResourceManager.GetString("DialogYubiKeyNotSupported", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyOnlyTouch {
            get {
                return ResourceManager.GetString("DialogYubiKeyOnlyTouch", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyPinDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyPinDefault", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyPinRequired {
            get {
                return ResourceManager.GetString("DialogYubiKeyPinRequired", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyPivSlotUsedFormat {
            get {
                return ResourceManager.GetString("DialogYubiKeyPivSlotUsedFormat", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyTouchPrompt {
            get {
                return ResourceManager.GetString("DialogYubiKeyTouchPrompt", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyOpenSecurity {
            get {
                return ResourceManager.GetString("DialogYubiKeyOpenSecurity", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeySelectMode {
            get {
                return ResourceManager.GetString("DialogYubiKeySelectMode", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyPukDefault {
            get {
                return ResourceManager.GetString("DialogYubiKeyPukDefault", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyEnabledFailed {
            get {
                return ResourceManager.GetString("DialogYubiKeyEnabledFailed", resourceCulture);
            }
        }
        
        internal static string DialogLabelAppSettingsDirectory {
            get {
                return ResourceManager.GetString("DialogLabelAppSettingsDirectory", resourceCulture);
            }
        }
        
        internal static string MenuRandomRename {
            get {
                return ResourceManager.GetString("MenuRandomRename", resourceCulture);
            }
        }
        
        internal static string ExpirationCheckWarning {
            get {
                return ResourceManager.GetString("ExpirationCheckWarning", resourceCulture);
            }
        }
        
        internal static string ToolTipGetLicense {
            get {
                return ResourceManager.GetString("ToolTipGetLicense", resourceCulture);
            }
        }
        
        internal static string DownloadFreeTrialQuestion {
            get {
                return ResourceManager.GetString("DownloadFreeTrialQuestion", resourceCulture);
            }
        }
        
        internal static string MenuTrialDownload {
            get {
                return ResourceManager.GetString("MenuTrialDownload", resourceCulture);
            }
        }
        
        internal static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        internal static string MenuSuggestPassword {
            get {
                return ResourceManager.GetString("MenuSuggestPassword", resourceCulture);
            }
        }
        
        internal static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        internal static string ToolTipCopySuggested {
            get {
                return ResourceManager.GetString("ToolTipCopySuggested", resourceCulture);
            }
        }
        
        internal static string ToolTipSuggestMasterPassword {
            get {
                return ResourceManager.GetString("ToolTipSuggestMasterPassword", resourceCulture);
            }
        }
        
        internal static string ToolTipShowPassword {
            get {
                return ResourceManager.GetString("ToolTipShowPassword", resourceCulture);
            }
        }
        
        internal static string ToolTipHidePassword {
            get {
                return ResourceManager.GetString("ToolTipHidePassword", resourceCulture);
            }
        }
        
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        internal static string ToolTipEmergencyReset {
            get {
                return ResourceManager.GetString("ToolTipEmergencyReset", resourceCulture);
            }
        }
        
        internal static string HeadingEmergencyReset {
            get {
                return ResourceManager.GetString("HeadingEmergencyReset", resourceCulture);
            }
        }
        
        internal static string MenuClearRecent {
            get {
                return ResourceManager.GetString("MenuClearRecent", resourceCulture);
            }
        }
        
        internal static string MenuEncryptDecryptText {
            get {
                return ResourceManager.GetString("MenuEncryptDecryptText", resourceCulture);
            }
        }
        
        internal static string ToolTipEncryptDecryptText {
            get {
                return ResourceManager.GetString("ToolTipEncryptDecryptText", resourceCulture);
            }
        }
        
        internal static string MessageFileFormatError {
            get {
                return ResourceManager.GetString("MessageFileFormatError", resourceCulture);
            }
        }
        
        internal static string WatermarkPasswordShare {
            get {
                return ResourceManager.GetString("WatermarkPasswordShare", resourceCulture);
            }
        }
        
        internal static string DialogTextCliApiVersionError {
            get {
                return ResourceManager.GetString("DialogTextCliApiVersionError", resourceCulture);
            }
        }
        
        internal static string ExpirationCheckPurchaseWarning {
            get {
                return ResourceManager.GetString("ExpirationCheckPurchaseWarning", resourceCulture);
            }
        }
        
        internal static string MessageTextForgotPassword {
            get {
                return ResourceManager.GetString("MessageTextForgotPassword", resourceCulture);
            }
        }
        
        internal static string DialogTitleSelectFilesToReEncrypt {
            get {
                return ResourceManager.GetString("DialogTitleSelectFilesToReEncrypt", resourceCulture);
            }
        }
        
        internal static string MenuReEncryptFiles {
            get {
                return ResourceManager.GetString("MenuReEncryptFiles", resourceCulture);
            }
        }
        
        internal static string MenuReEncryptFolder {
            get {
                return ResourceManager.GetString("MenuReEncryptFolder", resourceCulture);
            }
        }
        
        internal static string FilesCanceledMessage {
            get {
                return ResourceManager.GetString("FilesCanceledMessage", resourceCulture);
            }
        }
        
        internal static string OperationCanceledFormat {
            get {
                return ResourceManager.GetString("OperationCanceledFormat", resourceCulture);
            }
        }
        
        internal static string ToolTipGetLicenseNoCard {
            get {
                return ResourceManager.GetString("ToolTipGetLicenseNoCard", resourceCulture);
            }
        }
        
        internal static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        internal static string MenuInactivityExit {
            get {
                return ResourceManager.GetString("MenuInactivityExit", resourceCulture);
            }
        }
        
        internal static string MenuInactivityNever {
            get {
                return ResourceManager.GetString("MenuInactivityNever", resourceCulture);
            }
        }
        
        internal static string MenuInactivityTimeoutValueFormat {
            get {
                return ResourceManager.GetString("MenuInactivityTimeoutValueFormat", resourceCulture);
            }
        }
        
        internal static string ButtonLicense {
            get {
                return ResourceManager.GetString("ButtonLicense", resourceCulture);
            }
        }
        
        internal static string MenuClipboardLicense {
            get {
                return ResourceManager.GetString("MenuClipboardLicense", resourceCulture);
            }
        }
        
        internal static string DecryptionPasswordsAboutFormat {
            get {
                return ResourceManager.GetString("DecryptionPasswordsAboutFormat", resourceCulture);
            }
        }
        
        internal static string DialogTextPrivateKeysImported {
            get {
                return ResourceManager.GetString("DialogTextPrivateKeysImported", resourceCulture);
            }
        }
        
        internal static string PrivateKeysAboutFormat {
            get {
                return ResourceManager.GetString("PrivateKeysAboutFormat", resourceCulture);
            }
        }
        
        internal static string MenuCustomerPortal {
            get {
                return ResourceManager.GetString("MenuCustomerPortal", resourceCulture);
            }
        }
        
        internal static string MenuHelpVideos {
            get {
                return ResourceManager.GetString("MenuHelpVideos", resourceCulture);
            }
        }
        
        internal static string MessageTextBadLicenseString {
            get {
                return ResourceManager.GetString("MessageTextBadLicenseString", resourceCulture);
            }
        }
        
        internal static string MessageTextConfirmPasteDirectory {
            get {
                return ResourceManager.GetString("MessageTextConfirmPasteDirectory", resourceCulture);
            }
        }
        
        internal static string ConfirmationQuestion {
            get {
                return ResourceManager.GetString("ConfirmationQuestion", resourceCulture);
            }
        }
        
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        internal static string MenuClearDontShowAgain {
            get {
                return ResourceManager.GetString("MenuClearDontShowAgain", resourceCulture);
            }
        }
        
        internal static string MenuChangeEmail {
            get {
                return ResourceManager.GetString("MenuChangeEmail", resourceCulture);
            }
        }
        
        internal static string MixedFilesWarning {
            get {
                return ResourceManager.GetString("MixedFilesWarning", resourceCulture);
            }
        }
        
        internal static string MessageNotEncrypted {
            get {
                return ResourceManager.GetString("MessageNotEncrypted", resourceCulture);
            }
        }
        
        internal static string MessageZeroLength {
            get {
                return ResourceManager.GetString("MessageZeroLength", resourceCulture);
            }
        }
        
        internal static string DialogLabelRealStartFolder {
            get {
                return ResourceManager.GetString("DialogLabelRealStartFolder", resourceCulture);
            }
        }
        
        internal static string DialogTextExpiresSoonInfoFormat {
            get {
                return ResourceManager.GetString("DialogTextExpiresSoonInfoFormat", resourceCulture);
            }
        }
        
        internal static string DialogTextRemovableDriveFirstWarning {
            get {
                return ResourceManager.GetString("DialogTextRemovableDriveFirstWarning", resourceCulture);
            }
        }
        
        internal static string DialogTextRemovableDriveUnplugWarning {
            get {
                return ResourceManager.GetString("DialogTextRemovableDriveUnplugWarning", resourceCulture);
            }
        }
        
        internal static string DialogTitleRemovableDrive {
            get {
                return ResourceManager.GetString("DialogTitleRemovableDrive", resourceCulture);
            }
        }
        
        internal static string ZeroLengthWarning {
            get {
                return ResourceManager.GetString("ZeroLengthWarning", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyChangeConfiguration {
            get {
                return ResourceManager.GetString("DialogYubiKeyChangeConfiguration", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyDefaultChangeInfo {
            get {
                return ResourceManager.GetString("DialogYubiKeyDefaultChangeInfo", resourceCulture);
            }
        }
        
        internal static string ButtonCopyAll {
            get {
                return ResourceManager.GetString("ButtonCopyAll", resourceCulture);
            }
        }
        
        internal static string ButtonSaveAs {
            get {
                return ResourceManager.GetString("ButtonSaveAs", resourceCulture);
            }
        }
        
        internal static string ErrorCombiningShares {
            get {
                return ResourceManager.GetString("ErrorCombiningShares", resourceCulture);
            }
        }
        
        internal static string ErrorDuplicatesRemoved {
            get {
                return ResourceManager.GetString("ErrorDuplicatesRemoved", resourceCulture);
            }
        }
        
        internal static string LabelTheSecret {
            get {
                return ResourceManager.GetString("LabelTheSecret", resourceCulture);
            }
        }
        
        internal static string MenuCombineShares {
            get {
                return ResourceManager.GetString("MenuCombineShares", resourceCulture);
            }
        }
        
        internal static string MenuCreateShares {
            get {
                return ResourceManager.GetString("MenuCreateShares", resourceCulture);
            }
        }
        
        internal static string MenuLoadShares {
            get {
                return ResourceManager.GetString("MenuLoadShares", resourceCulture);
            }
        }
        
        internal static string PromptEnterFirstShare {
            get {
                return ResourceManager.GetString("PromptEnterFirstShare", resourceCulture);
            }
        }
        
        internal static string PromptEnterRemainingShares {
            get {
                return ResourceManager.GetString("PromptEnterRemainingShares", resourceCulture);
            }
        }
        
        internal static string PromptRequiredShares {
            get {
                return ResourceManager.GetString("PromptRequiredShares", resourceCulture);
            }
        }
        
        internal static string PromptTotalShares {
            get {
                return ResourceManager.GetString("PromptTotalShares", resourceCulture);
            }
        }
        
        internal static string SelectShareAny {
            get {
                return ResourceManager.GetString("SelectShareAny", resourceCulture);
            }
        }
        
        internal static string SelectShareSignIn {
            get {
                return ResourceManager.GetString("SelectShareSignIn", resourceCulture);
            }
        }
        
        internal static string ToolTipCombineShares {
            get {
                return ResourceManager.GetString("ToolTipCombineShares", resourceCulture);
            }
        }
        
        internal static string ToolTipCreateShares {
            get {
                return ResourceManager.GetString("ToolTipCreateShares", resourceCulture);
            }
        }
        
        internal static string ToolTipViewShares {
            get {
                return ResourceManager.GetString("ToolTipViewShares", resourceCulture);
            }
        }
        
        internal static string ViewSharesDescriptionFormat {
            get {
                return ResourceManager.GetString("ViewSharesDescriptionFormat", resourceCulture);
            }
        }
        
        internal static string WatermarkPasswordSecret {
            get {
                return ResourceManager.GetString("WatermarkPasswordSecret", resourceCulture);
            }
        }
        
        internal static string FeatureNotFreeShortInformation {
            get {
                return ResourceManager.GetString("FeatureNotFreeShortInformation", resourceCulture);
            }
        }
        
        internal static string FeatureNotFreeHideQuestion {
            get {
                return ResourceManager.GetString("FeatureNotFreeHideQuestion", resourceCulture);
            }
        }
        
        internal static string ReleaseNotesInformation {
            get {
                return ResourceManager.GetString("ReleaseNotesInformation", resourceCulture);
            }
        }
        
        internal static string RequestReviewQuestion {
            get {
                return ResourceManager.GetString("RequestReviewQuestion", resourceCulture);
            }
        }
        
        internal static string DialogTextEnterLicense {
            get {
                return ResourceManager.GetString("DialogTextEnterLicense", resourceCulture);
            }
        }
        
        internal static string WatermarkEnterLicenseHere {
            get {
                return ResourceManager.GetString("WatermarkEnterLicenseHere", resourceCulture);
            }
        }
        
        internal static string MenuEnterLicense {
            get {
                return ResourceManager.GetString("MenuEnterLicense", resourceCulture);
            }
        }
        
        internal static string DialogInstructionEnterLicenseFormat {
            get {
                return ResourceManager.GetString("DialogInstructionEnterLicenseFormat", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyServiceUnsupported {
            get {
                return ResourceManager.GetString("DialogYubiKeyServiceUnsupported", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyPcscMissing {
            get {
                return ResourceManager.GetString("DialogYubiKeyPcscMissing", resourceCulture);
            }
        }
        
        internal static string DialogYubiKeyRedistributableMissing {
            get {
                return ResourceManager.GetString("DialogYubiKeyRedistributableMissing", resourceCulture);
            }
        }
        
        internal static string CliVersionMismatchWarning {
            get {
                return ResourceManager.GetString("CliVersionMismatchWarning", resourceCulture);
            }
        }
    }
}
